#! /bin/bash

set -e

if ! command -v jq >/dev/null; then
    echo "0"
    echo "jq could not be found" 1>&2
    exit 1
fi

STABLE_GO_VERSIONS=$(
  curl -sL 'https://go.dev/dl/?mode=json' \
    | jq -r '.[].version' \
    | awk NF \
    | awk -F '.' '{print $1 "." $2}' \
    | tr '\n' ' '
)

CURRENT_GO_VERSION=$(
  go version \
    | awk '{print $3}' \
    | awk -F '.' '{print $1 "." $2}'
)

for version in ${STABLE_GO_VERSIONS}; do
  if [ "${CURRENT_GO_VERSION}" = "${version}" ]; then
    echo "1"
    exit 0
  fi
done

echo "0"
echo "Go version ${CURRENT_GO_VERSION} is not stable. Stable versions are: ${STABLE_GO_VERSIONS}" 1>&2
exit 1
